<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Admin-PC" failures="2" tests="3" name="ChromeTest(failed)" time="24.903" errors="0" timestamp="2022-09-20T14:34:20 IST">
  <testcase classname="pack2.FacebookTestClass2" name="testA" time="0.021">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at pack2.FacebookTestClass2.testA(FacebookTestClass2.java:67)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
  <testcase classname="pack2.FacebookTestClass2" name="verifyClickOnLogInPage" time="0.0">
    <skipped/>
  </testcase> <!-- verifyClickOnLogInPage -->
  <testcase classname="pack2.FacbookTestClass" name="verifyReturnToMessengerPage" time="9.43">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://www.messenger.com] but found [https://www.messenger.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.messenger.com] but found [https://www.messenger.com/]
at pack2.FacbookTestClass.verifyReturnToMessengerPage(FacbookTestClass.java:65)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- verifyReturnToMessengerPage -->
  <testcase classname="pack2.FacbookTestClass" name="verifyContactToHelpCenter" time="0.0">
    <ignored/>
  </testcase> <!-- verifyContactToHelpCenter -->
</testsuite> <!-- ChromeTest(failed) -->
